In [1]:
import numpy as np
import pandas as pd

In [2]:
# pandas => Dataframe
df = pd.read_csv('https://bit.ly/perch_csv_data')

In [3]:
perch_full = df.to_numpy()

In [4]:
perch_weight = np.array([5.9, 32.0, 40.0, 51.5, 70.0, 100.0, 78.0, 80.0, 85.0, 85.0, 110.0,
       115.0, 125.0, 130.0, 120.0, 120.0, 130.0, 135.0, 110.0, 130.0,
       150.0, 145.0, 150.0, 170.0, 225.0, 145.0, 188.0, 180.0, 197.0,
       218.0, 300.0, 260.0, 265.0, 250.0, 250.0, 300.0, 320.0, 514.0,
       556.0, 840.0, 685.0, 700.0, 700.0, 690.0, 900.0, 650.0, 820.0,
       850.0, 900.0, 1015.0, 820.0, 1100.0, 1000.0, 1100.0, 1000.0,
       1000.0])

In [5]:
from sklearn.model_selection import train_test_split

train_input, test_input, train_target, test_target = train_test_split(
    perch_full, perch_weight, random_state=42
)

In [8]:
from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures()

poly.fit([[2, 3]])
poly.transform([[2, 3]])

array([[1., 2., 3., 4., 6., 9.]])

In [9]:
3.0e+0

3.0

In [10]:
poly = PolynomialFeatures()
poly.fit(train_input)
train_poly = poly.transform(train_input)

In [11]:
test_poly = poly.transform(test_input)

In [12]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(train_poly, train_target)

LinearRegression()

In [13]:
lr.score(train_poly, train_target)

0.9903183436982125

In [14]:
lr.score(test_poly, test_target)

0.971455991159412

In [15]:
# 무조건 특성(파라미터)의 차원을 올려버릴 경우
poly = PolynomialFeatures(degree=5, include_bias=False)
train_5_poly = poly.fit_transform(train_input)
test_5_poly = poly.transform(test_input)

In [19]:
# 훈련 데이터에 대해서는 거의 완벽하게 나옴
lr.fit(train_5_poly, train_target)
lr.score(train_5_poly, train_target)

0.9999999999996176

In [20]:
# 테스트 데이터에서 말도 안되는 점수(Super Overfitting)
lr.score(test_5_poly, test_target)

-144.40585108215134

In [17]:
# 표준화 => 규제(과적합)

In [19]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
ss.fit(train_5_poly)
train_scaled = ss.transform(train_5_poly)
test_scaled = ss.transform(test_5_poly)


In [21]:
train_5_poly

array([[1.96000000e+01, 5.14000000e+00, 3.04000000e+00, ...,
        7.42244501e+02, 4.38992857e+02, 2.59637799e+02],
       [2.20000000e+01, 5.88000000e+00, 3.52000000e+00, ...,
        1.50793507e+03, 9.02709432e+02, 5.40397483e+02],
       [1.87000000e+01, 5.20000000e+00, 3.12000000e+00, ...,
        8.21240709e+02, 4.92744425e+02, 2.95646655e+02],
       ...,
       [2.56000000e+01, 6.56000000e+00, 4.24000000e+00, ...,
        3.28023719e+03, 2.12015331e+03, 1.37034299e+03],
       [4.20000000e+01, 1.28000000e+01, 6.87000000e+00, ...,
        5.31239245e+04, 2.85126063e+04, 1.53032504e+04],
       [3.45000000e+01, 1.02600000e+01, 6.39000000e+00, ...,
        2.74661189e+04, 1.71060916e+04, 1.06537939e+04]])

In [22]:
train_scaled

array([[-1.01339619, -1.01007487, -1.01952321, ..., -0.76449499,
        -0.75967179, -0.75143746],
       [-0.73842893, -0.75254307, -0.74466913, ..., -0.73198449,
        -0.72731765, -0.71950111],
       [-1.11650891, -0.98919391, -0.97371419, ..., -0.76114089,
        -0.75592147, -0.74734146],
       ...,
       [-0.32597805, -0.51589222, -0.33238802, ..., -0.65673421,
        -0.64237495, -0.62509499],
       [ 1.55296488,  1.65572732,  1.17358328, ...,  1.45958191,
         1.19906225,  0.95977016],
       [ 0.6936922 ,  0.7717668 ,  0.8987292 , ...,  0.3701756 ,
         0.40321427,  0.43089551]])